// playground/vue-quasar/src/presentation/components/renderers/TextField.vue
<template>
  <q-input
    v-if="!props.proxy.hidden"
    :model-value="String(props.value ?? '')"
    :label="label"
    :disable="props.proxy.disabled"
    :error="props.errors.length > 0"
    :error-message="props.errors[0]"
    outlined
    dense
    @update:model-value="props.onChange($event)"
    @blur="props.onBlur()"
    @focus="props.onFocus()"
  />
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import type { FieldRendererProps } from '@anhanga/vue'

const props = defineProps<FieldRendererProps>()
const { t, te } = useI18n()

const label = computed(() => {
  const key = `${props.domain}.fields.${props.name}`
  return te(key) ? t(key) : props.name
})
</script>

// playground/react-web/src/presentation/components/renderers/TextField.tsx
import { useTranslation } from "react-i18next";
import type { FieldRendererProps } from "@anhanga/react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { cn } from "@/lib/utils";

export function TextField({ domain, name, value, proxy, errors, onChange, onBlur, onFocus }: FieldRendererProps) {
  const { t, i18n } = useTranslation();
  if (proxy.hidden) return null;

  const fieldLabel = t(`${domain}.fields.${name}`, { defaultValue: name });
  const placeholderKey = `${domain}.fields.${name}.placeholder`;
  const placeholder = i18n.exists(placeholderKey) ? t(placeholderKey) : undefined;
  const hasError = errors.length > 0;

  return (
    <div className="mb-2 space-y-1.5">
      <Label className={cn(hasError && "text-destructive")}>{fieldLabel}</Label>
      <Input
        type="text"
        value={String(value ?? "")}
        onChange={(e) => onChange(e.target.value)}
        onBlur={onBlur}
        onFocus={onFocus}
        disabled={proxy.disabled}
        placeholder={placeholder}
        className={cn(hasError && "border-destructive focus-visible:ring-destructive")}
      />
      {errors.map((error, i) => (
        <p key={i} className="text-xs text-destructive">{error}</p>
      ))}
    </div>
  );
}
