// playground/sveltekit/src/routes/person/add/+page.svelte
<script lang="ts">
import { goto } from "$app/navigation";
import { scopes } from "$lib/routes/person";
import { personHandlers, personHooks } from "$lib/setup";
import { Scope } from "@anhanga/core";
import { allPermissions, personEvents, PersonSchema } from "@anhanga/demo";
import { createComponent, DataForm, DataPage } from "@anhanga/sveltekit";

const person = PersonSchema.provide();
const component = createComponent(Scope.add, scopes, goto);
</script>

<DataPage
  domain={person.domain}
  scope={Scope.add}
>
  <DataForm
    schema={person}
    scope={Scope.add}
    events={personEvents}
    handlers={personHandlers}
    hooks={personHooks}
    {component}
    permissions={allPermissions(person)}
  />
</DataPage>

// playground/react-native/app/person/add.tsx
import { Scope } from "@anhanga/core";
import { allPermissions, personEvents, PersonSchema } from "@anhanga/demo";
import { DataForm, DataPage, useComponent } from "@anhanga/react-native";
import { personHandlers, personHooks } from "../../src/demo";
import { scopes } from "./@routes";

export default function PersonAddPage () {
  const component = useComponent(Scope.add, scopes);

  return (
    <DataPage
      domain={PersonSchema.domain}
      scope={Scope.add}
    >
      <DataForm
        schema={PersonSchema.provide()}
        scope={Scope.add}
        events={personEvents}
        handlers={personHandlers}
        hooks={personHooks}
        component={component}
        permissions={allPermissions(PersonSchema.provide())}
        debug={true}
      />
    </DataPage>
  );
}
