// playground/sveltekit/src/routes/person/[id]/+page.svelte
<script lang="ts">
import { goto } from "$app/navigation";
import { page } from "$app/state";
import { scopes } from "$lib/routes/person";
import { personHandlers, personHooks } from "$lib/setup";
import { Scope } from "@anhanga/core";
import { allPermissions, personEvents, PersonSchema } from "@anhanga/demo";
import { createComponent, DataForm, DataPage } from "@anhanga/sveltekit";

const id = page.params.id;
const person = PersonSchema.provide();
const component = createComponent(Scope.view, scopes, goto);
</script>

<DataPage
  domain={person.domain}
  scope={Scope.view}
>
  <DataForm
    schema={person}
    scope={Scope.view}
    events={personEvents}
    handlers={personHandlers}
    hooks={personHooks}
    context={{ id }}
    {component}
    permissions={allPermissions(person)}
  />
</DataPage>

// playground/react-native/app/person/edit/[id].tsx
import { Scope } from "@anhanga/core";
import { allPermissions, personEvents, PersonSchema } from "@anhanga/demo";
import { DataForm, DataPage, useComponent } from "@anhanga/react-native";
import { useLocalSearchParams } from "expo-router";
import { personHandlers, personHooks } from "../../../src/demo";
import { scopes } from "../@routes";

export default function PersonEditPage () {
  const { id } = useLocalSearchParams<{ id: string }>();
  const component = useComponent(Scope.edit, scopes);
  const person = PersonSchema.provide();
  return (
    <DataPage
      domain={person.domain}
      scope={Scope.edit}
      permissions={allPermissions(person)}
    >
      <DataForm
        schema={person}
        scope={Scope.edit}
        events={personEvents}
        handlers={personHandlers}
        hooks={personHooks}
        context={{ id }}
        component={component}
        permissions={allPermissions(person)}
        debug={true}
      />
    </DataPage>
  );
}
