// packages/sveltekit/src/components/ActionButton.svelte
<script lang="ts">
  import type { ResolvedAction } from '@anhanga/svelte'
  import { resolveActionIcon } from '@anhanga/svelte'
  import { translate, hasTranslation } from '../i18n'

  let { action, domain, flat = false, small = false }: {
    action: ResolvedAction
    domain: string
    flat?: boolean
    small?: boolean
  } = $props()

  let label = $derived(() => {
    const commonKey = `common.actions.${action.name}`
    if (hasTranslation(commonKey)) return translate(commonKey)
    const domainKey = `${domain}.actions.${action.name}`
    if (hasTranslation(domainKey)) return translate(domainKey)
    return action.name
  })

  let iconComponent = $derived(() => {
    const resolved = resolveActionIcon(domain, action.name)
    if (!resolved) return null
    return resolved as import('svelte').ComponentType
  })

  let variant = $derived(() => action.config.variant ?? 'default')
</script>

<button
  class="btn btn-{variant()}"
  class:btn-flat={flat}
  class:btn-sm={small}
  onclick={() => action.execute()}
>
  {#if iconComponent()}
    <svelte:component this={iconComponent()} size={small ? 14 : 16} />
  {/if}
  {label()}
</button>

// packages/vue-quasar/src/components/ActionButton.vue
<template>
  <q-btn
      :label="label"
      :icon="resolvedIcon"
      :color="isDefault ? undefined : action.config.variant"
      :outline="isDefault && !flat"
      :unelevated="!isDefault && !flat"
      :flat="flat"
      :dense="dense"
      :size="size"
      no-caps
      class="schema-btn"
      @click="action.execute()"
  />
</template>

<script setup lang="ts">
import { QBtn } from 'quasar'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import type { ResolvedAction } from '@anhanga/vue'
import { resolveActionIcon } from '@anhanga/vue'

const props = withDefaults(defineProps<{
  action: ResolvedAction
  domain: string
  flat?: boolean
  dense?: boolean
  size?: string
}>(), {
  flat: false,
  dense: false,
  size: undefined,
})

const { t, te } = useI18n()

const label = computed(() => {
  const commonKey = `common.actions.${props.action.name}`
  if (te(commonKey)) return t(commonKey)
  const domainKey = `${props.domain}.actions.${props.action.name}`
  if (te(domainKey)) return t(domainKey)
  return props.action.name
})

const resolvedIcon = computed(() => {
  const icon = resolveActionIcon(props.domain, props.action.name)
  if (!icon) return undefined
  return icon as string
})

const isDefault = computed(() => props.action.config.variant === 'default')
</script>
