// packages/sveltekit/src/components/DataForm.svelte
<script lang="ts">
  import { useDataForm, getRenderer } from '@anhanga/svelte'
  import type { UseDataFormOptions } from '@anhanga/svelte'
  import { fill } from '@anhanga/core'
  import { translate, hasTranslation } from '../i18n'
  import ActionBar from './ActionBar.svelte'

  let props: UseDataFormOptions & { debug?: boolean } = $props()

  const defaultTranslate = (key: string, params?: Record<string, unknown>) => {
    if (!hasTranslation(key)) return key
    return translate(key, params)
  }

  const formStore = useDataForm({
    schema: props.schema,
    scope: props.scope,
    events: props.events,
    handlers: props.handlers,
    hooks: props.hooks,
    context: props.context,
    component: props.component,
    initialValues: props.initialValues,
    translate: props.translate ?? defaultTranslate,
    permissions: props.permissions,
  })

  let form = $derived($formStore)

  let debugExpanded = $state(false)
  let debug = $derived(props.debug ?? true)

  function resolveGroup (name: string) {
    const key = `${props.schema.domain}.groups.${name}`
    return hasTranslation(key) ? translate(key) : name
  }

  function handleFill () {
    formStore.setValues(fill(props.schema.fields, props.schema.identity))
  }
</script>

{#if form.loading}
  <div class="loading-overlay">Loading...</div>
{:else}
  <ActionBar actions={form.actions} position="top" domain={props.schema.domain} />

  {#each form.sections as section, index}
    {#if section.kind === 'group'}
      <div class="group-title">{resolveGroup(section.name)}</div>
    {/if}
    <div class="form-grid">
      {#each section.fields as field (field.name)}
        {#if !field.proxy.hidden}
          {@const renderer = getRenderer(field.config.component)}
          {@const fieldProps = form.getFieldProps(field.name)}
          {#if renderer}
            <div style="width: {field.proxy.width}%; min-width: 200px;">
              <svelte:component this={renderer} {...fieldProps} />
            </div>
          {/if}
        {/if}
      {/each}
    </div>
  {/each}

  <hr class="separator" />

  <ActionBar actions={form.actions} position="footer" domain={props.schema.domain} />

  {#if debug}
    <div class="debug-panel">
      <div class="debug-actions">
        <button class="debug-btn" onclick={handleFill}>Fill</button>
        <button class="debug-btn" onclick={() => formStore.reset()}>Reset</button>
        <button class="debug-btn" onclick={() => formStore.validate()}>Validate</button>
        <button class="debug-btn" onclick={() => globalThis.location.reload()}>Reload</button>
        <button class="debug-btn" onclick={() => debugExpanded = !debugExpanded}>
          {debugExpanded ? '−' : '+'}
        </button>
      </div>

      {#if debugExpanded}
        <div class="debug-label">State</div>
        <pre>{JSON.stringify(form.state, null, 2)}</pre>
        <div class="debug-label">Errors</div>
        <pre>{JSON.stringify(form.errors, null, 2)}</pre>
        <div class="debug-label">
          dirty: {form.dirty} | valid: {form.valid}
        </div>
      {/if}
    </div>
  {/if}
{/if}

// packages/vue-quasar/src/components/DataForm.vue
<template>
  <div
      v-if="form.loading"
      class="text-center q-pa-lg text-grey"
  >
    <q-spinner
        size="2em"
        class="q-mr-sm"
    />
    Loading...
  </div>

  <div v-else>
    <ActionBar
        :actions="form.actions"
        position="top"
        :domain="props.schema.domain"
    />

    <div
        v-for="(section, index) in form.sections"
        :key="section.kind === 'group' ? section.name : `ungrouped-${index}`"
        class="q-mb-lg"
    >
      <div
          v-if="section.kind === 'group'"
          class="q-mb-sm text-subtitle2 text-grey-7"
      >
        {{ resolveGroup(section.name) }}
      </div>
      <div class="row q-col-gutter-md">
        <template
            v-for="field in section.fields"
            :key="field.name"
        >
          <div
              v-if="!field.proxy.hidden"
              :class="`col-${Math.round(field.proxy.width * 12 / 100)}`"
          >
            <component
                :is="getRenderer(field.config.component)"
                v-if="getRenderer(field.config.component)"
                v-bind="form.getFieldProps(field.name)"
            />
          </div>
        </template>
      </div>
    </div>

    <q-separator class="q-my-lg" />

    <ActionBar
        :actions="form.actions"
        position="footer"
        :domain="props.schema.domain"
    />

    <div
        v-if="debug"
        class="q-mt-lg q-pa-md bg-dark rounded-borders"
    >
      <div class="row q-gutter-xs q-mb-sm">
        <q-btn
            dense
            flat
            icon="flash_on"
            size="sm"
            color="amber"
            @click="handleFill"
        />
        <q-btn
            dense
            flat
            icon="restart_alt"
            size="sm"
            color="grey"
            @click="form.reset()"
        />
        <q-btn
            dense
            flat
            icon="check"
            size="sm"
            color="green"
            @click="form.validate()"
        />
        <q-btn
            dense
            flat
            icon="refresh"
            size="sm"
            color="blue"
            @click="handleReload"
        />
        <q-btn
            dense
            flat
            :icon="debugExpanded ? 'remove' : 'add'"
            size="sm"
            color="amber"
            @click="debugExpanded = !debugExpanded"
        />
      </div>

      <template v-if="debugExpanded">
        <div class="text-caption text-grey-5 q-mt-sm">State</div>
        <pre
            class="text-caption text-grey-3"
            style="white-space: pre-wrap"
        >{{ JSON.stringify(form.state, null, 2) }}</pre>
        <div class="text-caption text-grey-5 q-mt-sm">Errors</div>
        <pre
            class="text-caption text-grey-3"
            style="white-space: pre-wrap"
        >{{ JSON.stringify(form.errors, null, 2) }}</pre>
        <div class="text-caption text-grey-5 q-mt-sm">
          dirty: {{ form.dirty }} | valid: {{ form.valid }}
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useDataForm, getRenderer } from '@anhanga/vue'
import type { UseDataFormOptions } from '@anhanga/vue'
import { fill } from '@anhanga/core'
import ActionBar from './ActionBar.vue'

interface DataFormProps extends UseDataFormOptions {
  debug?: boolean
}

const props = withDefaults(defineProps<DataFormProps>(), {
  debug: true,
})

const { t, te } = useI18n()
const translateFn = (key: string, params?: Record<string, unknown>) => {
  if (!te(key)) return key
  return t(key, params ?? {})
}

const form = useDataForm({ ...props, translate: props.translate ?? translateFn })
const debugExpanded = ref(false)

function resolveGroup (name: string) {
  const key = `${props.schema.domain}.groups.${name}`
  return te(key) ? t(key) : name
}

function handleFill () {
  form.setValues(fill(props.schema.fields, props.schema.identity))
}

function handleReload () {
  window.location.reload()
}
</script>
