// packages/sveltekit/src/renderers/ListField.svelte
<script lang="ts">
  import { translate, hasTranslation } from '../i18n'

  let { domain, name, value, config, proxy, errors, onChange }: {
    domain: string
    name: string
    value: unknown
    config: { attrs: Record<string, unknown> }
    proxy: { hidden: boolean; disabled: boolean }
    errors: string[]
    onChange: (v: unknown) => void
    onBlur: () => void
    onFocus: () => void
  } = $props()

  let label = $derived(() => {
    const key = `${domain}.fields.${name}`
    return hasTranslation(key) ? translate(key) : name
  })

  let items = $derived(Array.isArray(value) ? (value as Record<string, unknown>[]) : [])
  let reorderable = $derived(config.attrs.reorderable === true)

  function remove(index: number) {
    onChange(items.filter((_, i) => i !== index))
  }

  function add() {
    onChange([...items, {}])
  }

  function moveUp(index: number) {
    if (index === 0) return
    const next = [...items];
    [next[index - 1], next[index]] = [next[index], next[index - 1]]
    onChange(next)
  }

  function moveDown(index: number) {
    if (index >= items.length - 1) return
    const next = [...items];
    [next[index], next[index + 1]] = [next[index + 1], next[index]]
    onChange(next)
  }
</script>

{#if !proxy.hidden}
  <div class="form-field" class:has-error={errors.length > 0}>
    <label>{label()}</label>
    <div class="list-container">
      {#each items as item, index}
        <div class="list-row">
          <span class="row-index">#{index + 1}</span>
          <span class="row-preview">
            {Object.values(item).filter(Boolean).join(', ') || '—'}
          </span>
          <div class="row-actions">
            {#if reorderable}
              <button type="button" onclick={() => moveUp(index)} disabled={proxy.disabled || index === 0}>↑</button>
              <button type="button" onclick={() => moveDown(index)} disabled={proxy.disabled || index >= items.length - 1}>↓</button>
            {/if}
            {#if !proxy.disabled}
              <button type="button" class="btn-destructive" onclick={() => remove(index)}>×</button>
            {/if}
          </div>
        </div>
      {/each}
    </div>
    {#if !proxy.disabled}
      <button type="button" class="add-btn" onclick={add}>+</button>
    {/if}
    {#if errors.length > 0}
      <span class="field-error">{errors[0]}</span>
    {/if}
  </div>
{/if}

// packages/vue-quasar/src/renderers/ListField.vue
<template>
  <div v-if="!props.proxy.hidden" class="list-field">
    <label class="list-label">{{ label }}</label>
    <q-list bordered separator>
      <q-item v-for="(item, index) in items" :key="index">
        <q-item-section side>
          <span class="text-caption">#{{ index + 1 }}</span>
        </q-item-section>
        <q-item-section>
          {{ Object.values(item).filter(Boolean).join(', ') || '—' }}
        </q-item-section>
        <q-item-section side>
          <div class="row no-wrap q-gutter-xs">
            <template v-if="reorderable">
              <q-btn flat dense icon="arrow_upward" size="sm" :disable="props.proxy.disabled || index === 0" @click="moveUp(index)" />
              <q-btn flat dense icon="arrow_downward" size="sm" :disable="props.proxy.disabled || index >= items.length - 1" @click="moveDown(index)" />
            </template>
            <q-btn v-if="!props.proxy.disabled" flat dense icon="close" size="sm" color="negative" @click="remove(index)" />
          </div>
        </q-item-section>
      </q-item>
    </q-list>
    <q-btn v-if="!props.proxy.disabled" flat dense icon="add" class="full-width q-mt-xs" @click="add" />
    <div v-if="props.errors.length > 0" class="text-negative text-caption q-mt-xs">{{ props.errors[0] }}</div>
  </div>
</template>

<script setup lang="ts">
import { QList, QItem, QItemSection, QBtn } from 'quasar'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import type { FieldRendererProps } from '@ybyra/vue'

const props = defineProps<FieldRendererProps>()
const { t, te } = useI18n()

const label = computed(() => {
  const key = `${props.domain}.fields.${props.name}`
  return te(key) ? t(key) : props.name
})

const items = computed(() => Array.isArray(props.value) ? (props.value as Record<string, unknown>[]) : [])
const reorderable = computed(() => props.config.attrs.reorderable === true)

function remove(index: number) {
  props.onChange(items.value.filter((_, i) => i !== index))
}

function add() {
  props.onChange([...items.value, {}])
}

function moveUp(index: number) {
  if (index === 0) return
  const next = [...items.value];
  [next[index - 1], next[index]] = [next[index], next[index - 1]]
  props.onChange(next)
}

function moveDown(index: number) {
  if (index >= items.value.length - 1) return
  const next = [...items.value];
  [next[index], next[index + 1]] = [next[index + 1], next[index]]
  props.onChange(next)
}
</script>
