// packages/playground/app/person/index.tsx
import { useMemo } from "react";
import { useTranslation } from "react-i18next";
import { Scope } from "@anhanga/core";
import { PersonSchema } from "../../src/domain/person/schema";
import { personHandlers } from "../../src/domain/person/handlers";
import { personHooks } from "../../src/domain/person/hooks";
import { createComponent } from "../../src/presentation/contracts/component";
import { useDialog } from "../../src/presentation/components/Dialog";
import { SchemaTable } from "../../src/presentation/components/SchemaTable";
import { Page } from "../../src/presentation/components/Page";
import { scopes } from "./@routes";

export default function PersonIndexPage () {
  const { t } = useTranslation();
  const dialog = useDialog();
  const component = useMemo(
    () => createComponent(Scope.index, scopes, dialog),
    [dialog],
  );

  return (
    <Page
      domain={PersonSchema.domain}
      scope={Scope.index}
    >
      <SchemaTable
        grid={false}
        schema={PersonSchema.provide()}
        scope={Scope.index}
        handlers={personHandlers}
        hooks={personHooks}
        component={component}
        translate={t}
        pageSize={3}
        debug={false}
      />
    </Page>
  );
}

// playground/sveltekit/src/routes/person/+page.svelte
<script lang="ts">
  import { Scope } from '@anhanga/core'
  import { PersonSchema } from '@anhanga/demo'
  import { personHandlers, personHooks } from '$lib/setup'
  import { createComponent } from '$lib/presentation/contracts/component'
  import { translate, hasTranslation } from '$lib/i18n'
  import SchemaTable from '$lib/presentation/components/SchemaTable.svelte'

  const scopes = {
    [Scope.index]: { path: '/person' },
    [Scope.add]: { path: '/person/add' },
    [Scope.view]: { path: '/person/:id' },
    [Scope.edit]: { path: '/person/:id/edit' },
  }

  const dialog = {
    async confirm (message: string) { return window.confirm(message) },
    async alert (message: string) { window.alert(message) },
  }

  const component = createComponent(Scope.index, scopes, dialog)

  const translateFn = (key: string, params?: Record<string, unknown>) => {
    if (!hasTranslation(key)) return key
    return translate(key, params)
  }
</script>

<div class="card">
  <div class="card-title">{translate('person.title')}</div>
  <SchemaTable
    schema={PersonSchema.provide()}
    scope={Scope.index}
    handlers={personHandlers}
    hooks={personHooks}
    {component}
    translate={translateFn}
    pageSize={3}
  />
</div>
