// playground/sveltekit/src/lib/presentation/components/renderers/DateField.svelte
<script lang="ts">
  import { translate, hasTranslation } from '$lib/i18n'

  let { domain, name, value, proxy, errors, onChange, onBlur, onFocus }: {
    domain: string
    name: string
    value: unknown
    proxy: { hidden: boolean; disabled: boolean }
    errors: string[]
    onChange: (v: unknown) => void
    onBlur: () => void
    onFocus: () => void
  } = $props()

  let label = $derived(() => {
    const key = `${domain}.fields.${name}`
    return hasTranslation(key) ? translate(key) : name
  })
</script>

{#if !proxy.hidden}
  <div class="form-field" class:has-error={errors.length > 0}>
    <label for={name}>{label()}</label>
    <input
      id={name}
      type="date"
      value={String(value ?? '')}
      disabled={proxy.disabled}
      oninput={(e) => onChange(e.currentTarget.value)}
      onblur={() => onBlur()}
      onfocus={() => onFocus()}
    />
    {#if errors.length > 0}
      <span class="field-error">{errors[0]}</span>
    {/if}
  </div>
{/if}

// playground/vue-quasar/src/presentation/components/renderers/DateField.vue
<template>
  <q-input
    v-if="!props.proxy.hidden"
    :model-value="String(props.value ?? '')"
    :label="label"
    :disable="props.proxy.disabled"
    :error="props.errors.length > 0"
    :error-message="props.errors[0]"
    type="date"
    outlined
    dense
    @update:model-value="props.onChange($event)"
    @blur="props.onBlur()"
    @focus="props.onFocus()"
  />
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import type { FieldRendererProps } from '@anhanga/vue'

const props = defineProps<FieldRendererProps>()
const { t, te } = useI18n()

const label = computed(() => {
  const key = `${props.domain}.fields.${props.name}`
  return te(key) ? t(key) : props.name
})
</script>
