// packages/vue-quasar/src/components/ActionBar.vue
<template>
  <div
      v-if="filtered.length > 0"
      class="row justify-between items-center q-mb-md"
  >
    <div class="row q-gutter-sm">
      <ActionButton
          v-for="action in startActions"
          :key="action.name"
          :action="action"
          :domain="props.domain"
      />
    </div>
    <div class="row q-gutter-sm">
      <ActionButton
          v-for="action in endActions"
          :key="action.name"
          :action="action"
          :domain="props.domain"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { ResolvedAction } from '@anhanga/vue'
import type { PositionValue } from '@anhanga/core'
import ActionButton from './ActionButton.vue'

const props = defineProps<{
  actions: ResolvedAction[]
  position: PositionValue
  domain: string
}>()

const filtered = computed(() =>
    props.actions.filter((a) => a.config.positions?.includes(props.position)),
)

const startActions = computed(() =>
    filtered.value.filter((a) => a.config.align === 'start'),
)

const endActions = computed(() =>
    filtered.value.filter((a) => a.config.align === 'end'),
)
</script>

// packages/sveltekit/src/components/ActionBar.svelte
<script lang="ts">
  import type { ResolvedAction } from '@anhanga/svelte'
  import type { PositionValue } from '@anhanga/core'
  import ActionButton from './ActionButton.svelte'

  let { actions, position, domain }: {
    actions: ResolvedAction[]
    position: PositionValue
    domain: string
  } = $props()

  let filtered = $derived(() =>
    actions.filter((a) => a.config.positions?.includes(position)),
  )

  let startActions = $derived(() =>
    filtered().filter((a) => a.config.align === 'start'),
  )

  let endActions = $derived(() =>
    filtered().filter((a) => a.config.align === 'end'),
  )
</script>

{#if filtered().length > 0}
  <div class="action-bar">
    <div class="action-group">
      {#each startActions() as action (action.name)}
        <ActionButton {action} {domain} />
      {/each}
    </div>
    <div class="action-group">
      {#each endActions() as action (action.name)}
        <ActionButton {action} {domain} />
      {/each}
    </div>
  </div>
{/if}
