// packages/vue-quasar/src/components/DataPage.vue
<template>
  <q-card>
    <q-card-section>
      <div class="text-h6">{{ title }}</div>
    </q-card-section>

    <q-card-section>
      <slot />
    </q-card-section>
  </q-card>
</template>

<script
  setup
  lang="ts"
>
import type { ScopeValue } from "@anhanga/core";
import { computed } from "vue";
import { useI18n } from "vue-i18n";

const props = defineProps<{
  domain: string
  scope: ScopeValue
}>();

const { t, te } = useI18n();

const title = computed(() => {
  const domainTitle = te(`${props.domain}.title`) ? t(`${props.domain}.title`) : props.domain;
  const scopeLabel = te(`common.scopes.${props.scope}`) ? t(`common.scopes.${props.scope}`) : "";
  if (!scopeLabel) return domainTitle;
  return `${domainTitle} — ${scopeLabel}`;
});
</script>

// packages/sveltekit/src/components/DataPage.svelte
<script lang="ts">
  import type { ScopeValue } from '@anhanga/core'
  import { translate, hasTranslation } from '../i18n'
  import type { Snippet } from 'svelte'

  let { domain, scope, children }: {
    domain: string
    scope: ScopeValue
    children: Snippet
  } = $props()

  let title = $derived(() => {
    const domainKey = `${domain}.title`
    const base = hasTranslation(domainKey) ? translate(domainKey) : domain
    const scopeKey = `common.scopes.${scope}`
    if (scope === 'index' || !hasTranslation(scopeKey)) return base
    return `${base} \u2014 ${translate(scopeKey)}`
  })
</script>

<div class="card">
  <div class="card-title">{title()}</div>
  {@render children()}
</div>
