// packages/sveltekit/src/renderers/ListField.svelte
<script lang="ts">
  import { translate, hasTranslation } from '../i18n'
  import { getRenderer } from '@ybyra/svelte'
  import { useDataForm } from '@ybyra/svelte'
  import type { UseDataFormStore } from '@ybyra/svelte'
  import type { SchemaProvide, ScopeValue, ComponentContract } from '@ybyra/core'

  let { domain, name, value, config, proxy, errors, onChange, scope }: {
    domain: string
    name: string
    value: unknown
    config: { attrs: Record<string, unknown> }
    proxy: { hidden: boolean; disabled: boolean }
    errors: string[]
    onChange: (v: unknown) => void
    onBlur: () => void
    onFocus: () => void
    scope: string
  } = $props()

  let label = $derived(() => {
    const key = `${domain}.fields.${name}`
    return hasTranslation(key) ? translate(key) : name
  })

  let items = $derived(Array.isArray(value) ? (value as Record<string, unknown>[]) : [])
  let reorderable = $derived(config.attrs.reorderable === true)
  let itemSchema = $derived(() => {
    const raw = config.attrs.itemSchema
    return raw && typeof raw === 'object' && 'fields' in raw && 'domain' in raw
      ? (raw as SchemaProvide)
      : undefined
  })

  let showAdd = $state(false)
  let editIndex = $state<number | null>(null)

  // Sub-form store (Svelte Readable)
  let formStore = $state<UseDataFormStore | null>(null)
  // Reactive subscription to the store value
  let form = $derived(formStore ? $formStore : null)

  const noopComponent: ComponentContract = {
    scope: scope as ScopeValue,
    scopes: {} as Record<string, { path: string }>,
    reload: () => {},
    navigator: { push: () => {}, back: () => {}, replace: () => {} },
    dialog: { confirm: async () => true, alert: async () => {} },
    toast: { success: () => {}, error: () => {}, warning: () => {}, info: () => {} },
    loading: { show: () => {}, hide: () => {} },
  }

  function openAdd() {
    const schema = itemSchema()
    if (schema) {
      formStore = useDataForm({
        schema,
        scope: scope as ScopeValue,
        component: noopComponent,
      })
      showAdd = true
    } else {
      onChange([...items, {}])
    }
  }

  function openEdit(index: number) {
    const schema = itemSchema()
    if (!schema) return
    formStore = useDataForm({
      schema,
      scope: scope as ScopeValue,
      component: noopComponent,
      initialValues: items[index],
    })
    editIndex = index
  }

  function saveNew() {
    if (!form) return
    if (formStore!.validate()) {
      onChange([...$state.snapshot(items), { ...form.state }])
      cancelModal()
    }
  }

  function saveEdit() {
    if (!form || editIndex === null) return
    if (formStore!.validate()) {
      const next = [...$state.snapshot(items)]
      next[editIndex] = { ...form.state }
      onChange(next)
      cancelModal()
    }
  }

  function cancelModal() {
    showAdd = false
    editIndex = null
    formStore = null
  }

  function remove(index: number) {
    onChange(items.filter((_, i) => i !== index))
  }

  function moveUp(index: number) {
    if (index === 0) return
    const next = [...items];
    [next[index - 1], next[index]] = [next[index], next[index - 1]]
    onChange(next)
  }

  function moveDown(index: number) {
    if (index >= items.length - 1) return
    const next = [...items];
    [next[index], next[index + 1]] = [next[index + 1], next[index]]
    onChange(next)
  }

  let modalOpen = $derived(showAdd || editIndex !== null)
</script>

{#if !proxy.hidden}
  <div class="form-field" class:has-error={errors.length > 0}>
    <label>{label()}</label>
    <div class="list-container">
      {#each items as item, index}
        <div class="list-row">
          <span class="row-index">#{index + 1}</span>
          <span class="row-preview">
            {Object.values(item).filter(Boolean).join(', ') || '—'}
          </span>
          <div class="row-actions">
            {#if itemSchema() && !proxy.disabled}
              <button type="button" onclick={() => openEdit(index)}>✎</button>
            {/if}
            {#if reorderable}
              <button type="button" onclick={() => moveUp(index)} disabled={proxy.disabled || index === 0}>↑</button>
              <button type="button" onclick={() => moveDown(index)} disabled={proxy.disabled || index >= items.length - 1}>↓</button>
            {/if}
            {#if !proxy.disabled}
              <button type="button" class="btn-destructive" onclick={() => remove(index)}>×</button>
            {/if}
          </div>
        </div>
      {/each}
    </div>
    {#if !proxy.disabled}
      <button type="button" class="add-btn" onclick={openAdd}>+</button>
    {/if}
    {#if errors.length > 0}
      <span class="field-error">{errors[0]}</span>
    {/if}
  </div>
{/if}

{#if modalOpen && form}
  <!-- svelte-ignore a11y_no_noninteractive_tabindex -->
  <div class="modal-overlay" role="dialog" tabindex="-1" onclick={cancelModal} onkeydown={(e) => e.key === 'Escape' && cancelModal()}>
    <div class="modal-card" onclick={(e) => e.stopPropagation()}>
      <div class="modal-title">
        {editIndex !== null
          ? (hasTranslation('common.list.editItem') ? translate('common.list.editItem') : 'Edit item')
          : (hasTranslation('common.list.addItem') ? translate('common.list.addItem') : 'Add item')}
      </div>
      <div class="modal-body">
        {#each form.fields as field (field.name)}
          {#if !field.proxy.hidden}
            {@const renderer = getRenderer(field.config.component)}
            {#if renderer}
              <svelte:component this={renderer} {...form.getFieldProps(field.name)} />
            {/if}
          {/if}
        {/each}
      </div>
      <div class="modal-actions">
        <button type="button" class="modal-cancel" onclick={cancelModal}>{hasTranslation('common.dialog.cancel') ? translate('common.dialog.cancel') : 'Cancel'}</button>
        <button type="button" class="modal-ok" onclick={editIndex !== null ? saveEdit : saveNew}>{hasTranslation('common.dialog.ok') ? translate('common.dialog.ok') : 'OK'}</button>
      </div>
    </div>
  </div>
{/if}

<style>
  .modal-overlay {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 9999;
  }
  .modal-card {
    background: var(--card, white);
    border-radius: 0.75rem;
    padding: 1.5rem;
    min-width: 400px;
    max-width: 640px;
    max-height: 80vh;
    overflow: auto;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  }
  .modal-title {
    font-size: 1.125rem;
    font-weight: 600;
    margin-bottom: 1rem;
  }
  .modal-body {
    margin-bottom: 1.5rem;
  }
  .modal-actions {
    display: flex;
    justify-content: flex-end;
    gap: 0.5rem;
  }
  .modal-cancel, .modal-ok {
    padding: 0.5rem 1rem;
    border-radius: 0.375rem;
    border: none;
    cursor: pointer;
    font-size: 0.875rem;
    font-weight: 500;
    min-width: 80px;
    text-align: center;
  }
  .modal-cancel {
    background: var(--secondary, #f0f0f0);
    color: var(--secondary-foreground, #333);
  }
  .modal-ok {
    background: var(--primary, #3b82f6);
    color: var(--primary-foreground, white);
  }
</style>

// packages/react-web/src/renderers/ListField.tsx
import { useState, useMemo } from "react";
import { createPortal } from "react-dom";
import { useTranslation } from "react-i18next";
import type { FieldRendererProps } from "@ybyra/react";
import { getRenderer, useDataForm } from "@ybyra/react";
import type { SchemaProvide, Scope } from "@ybyra/core";
import { useTheme } from "../theme/context";
import type { Theme } from "../theme/default";
import { ds } from "../support/ds";

function ItemFormModal({
  itemSchema,
  scope,
  initialValues,
  onSave,
  onCancel,
}: {
  itemSchema: SchemaProvide;
  scope: string;
  initialValues?: Record<string, unknown>;
  onSave: (values: Record<string, unknown>) => void;
  onCancel: () => void;
}) {
  const { t } = useTranslation();
  const theme = useTheme();
  const modalStyles = createModalStyles(theme);

  const noopComponent = useMemo(() => ({
    scope: scope as typeof Scope[keyof typeof Scope],
    scopes: {} as Record<string, { path: string }>,
    reload: () => {},
    navigator: { push: () => {}, back: () => {}, replace: () => {} },
    dialog: { confirm: async () => true, alert: async () => {} },
    toast: { success: () => {}, error: () => {}, warning: () => {}, info: () => {} },
    loading: { show: () => {}, hide: () => {} },
  }), [scope]);

  const form = useDataForm({
    schema: itemSchema,
    scope: scope as typeof Scope[keyof typeof Scope],
    component: noopComponent,
    initialValues,
  });

  const handleSave = () => {
    if (form.validate()) {
      onSave(form.state);
    }
  };

  return createPortal(
    <div style={modalStyles.overlay} onClick={onCancel}>
      <div style={modalStyles.card} onClick={(e) => e.stopPropagation()}>
        <div style={modalStyles.title}>
          {initialValues ? t("common.list.editItem", { defaultValue: "Edit item" }) : t("common.list.addItem", { defaultValue: "Add item" })}
        </div>
        <div style={modalStyles.body}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(100, 1fr)" }}>
            {form.fields.map((field) => {
              if (field.proxy.hidden) return null;
              const Renderer = getRenderer(field.config.component);
              if (!Renderer) return null;
              return (
                <div key={field.name} style={{ gridColumn: `span ${field.proxy.width}` }}>
                  <Renderer {...form.getFieldProps(field.name)} />
                </div>
              );
            })}
          </div>
        </div>
        <div style={modalStyles.actions}>
          <button type="button" style={modalStyles.cancelButton} onClick={onCancel}>
            {t("common.dialog.cancel", { defaultValue: "Cancel" })}
          </button>
          <button type="button" style={modalStyles.okButton} onClick={handleSave}>
            {t("common.dialog.ok", { defaultValue: "OK" })}
          </button>
        </div>
      </div>
    </div>,
    document.body,
  );
}

export function ListField({ domain, name, value, config, proxy, errors, onChange, scope }: FieldRendererProps) {
  const { t } = useTranslation();
  const theme = useTheme();
  const styles = createStyles(theme);
  const [editIndex, setEditIndex] = useState<number | null>(null);
  const [showAdd, setShowAdd] = useState(false);
  if (proxy.hidden) return null;

  const fieldLabel = t(`${domain}.fields.${name}`, { defaultValue: name });
  const hasError = errors.length > 0;
  const items = Array.isArray(value) ? (value as Record<string, unknown>[]) : [];
  const reorderable = config.attrs.reorderable === true;
  const rawSchema = config.attrs.itemSchema;
  const itemSchema = rawSchema && typeof rawSchema === 'object' && 'fields' in rawSchema && 'domain' in rawSchema
    ? (rawSchema as SchemaProvide)
    : undefined;

  const remove = (index: number) => {
    onChange(items.filter((_, i) => i !== index));
  };

  const add = () => {
    if (itemSchema) {
      setShowAdd(true);
    } else {
      onChange([...items, {}]);
    }
  };

  const moveUp = (index: number) => {
    if (index === 0) return;
    const next = [...items];
    [next[index - 1], next[index]] = [next[index], next[index - 1]];
    onChange(next);
  };

  const moveDown = (index: number) => {
    if (index >= items.length - 1) return;
    const next = [...items];
    [next[index], next[index + 1]] = [next[index + 1], next[index]];
    onChange(next);
  };

  const handleSaveNew = (values: Record<string, unknown>) => {
    onChange([...items, values]);
    setShowAdd(false);
  };

  const handleSaveEdit = (values: Record<string, unknown>) => {
    if (editIndex === null) return;
    const next = [...items];
    next[editIndex] = values;
    onChange(next);
    setEditIndex(null);
  };

  return (
    <div style={styles.container} {...ds(`ListField:${name}`)}>
      <label style={{ ...styles.label, ...(hasError ? styles.labelError : {}) }}>{fieldLabel}</label>
      <div style={styles.list}>
        {items.map((item, index) => (
          <div key={index} style={styles.row}>
            <span style={styles.rowIndex}>#{index + 1}</span>
            <span style={styles.rowPreview}>
              {Object.values(item).filter(Boolean).join(", ") || "—"}
            </span>
            <div style={styles.rowActions}>
              {itemSchema && !proxy.disabled && (
                <button type="button" style={styles.btn} onClick={() => setEditIndex(index)}>✎</button>
              )}
              {reorderable && (
                <>
                  <button type="button" style={styles.btn} onClick={() => moveUp(index)} disabled={proxy.disabled || index === 0}>↑</button>
                  <button type="button" style={styles.btn} onClick={() => moveDown(index)} disabled={proxy.disabled || index >= items.length - 1}>↓</button>
                </>
              )}
              {!proxy.disabled && (
                <button type="button" style={{ ...styles.btn, ...styles.btnDestructive }} onClick={() => remove(index)}>×</button>
              )}
            </div>
          </div>
        ))}
      </div>
      {!proxy.disabled && (
        <button type="button" style={styles.addBtn} onClick={add}>+</button>
      )}
      <div style={styles.errorSlot}>
        {errors.map((error, i) => (
          <p key={i} style={styles.error}>{error}</p>
        ))}
      </div>

      {showAdd && itemSchema && (
        <ItemFormModal
          itemSchema={itemSchema}
          scope={scope}
          onSave={handleSaveNew}
          onCancel={() => setShowAdd(false)}
        />
      )}

      {editIndex !== null && itemSchema && (
        <ItemFormModal
          key={editIndex}
          itemSchema={itemSchema}
          scope={scope}
          initialValues={items[editIndex]}
          onSave={handleSaveEdit}
          onCancel={() => setEditIndex(null)}
        />
      )}
    </div>
  );
}

const createStyles = (theme: Theme) => ({
  container: {
    padding: `0 ${theme.spacing.xs}px`,
  },
  label: {
    display: "block",
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.semibold,
    marginBottom: theme.spacing.xs,
    color: theme.colors.foreground,
  },
  labelError: {
    color: theme.colors.destructive,
  },
  list: {
    border: `1px solid ${theme.colors.input}`,
    borderRadius: theme.borderRadius.md,
    overflow: "hidden",
  },
  row: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing.xs,
    padding: `${theme.spacing.xs}px ${theme.spacing.md}px`,
    borderBottom: `1px solid ${theme.colors.input}`,
    backgroundColor: theme.colors.card,
  },
  rowIndex: {
    fontSize: theme.fontSize.xs,
    color: theme.colors.mutedForeground,
    minWidth: 24,
  },
  rowPreview: {
    flex: 1,
    fontSize: theme.fontSize.sm,
    color: theme.colors.cardForeground,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  rowActions: {
    display: "flex",
    gap: 4,
  },
  btn: {
    border: `1px solid ${theme.colors.input}`,
    borderRadius: theme.borderRadius.sm,
    backgroundColor: theme.colors.card,
    color: theme.colors.cardForeground,
    cursor: "pointer",
    padding: "2px 6px",
    fontSize: theme.fontSize.xs,
  },
  btnDestructive: {
    color: theme.colors.destructive,
  },
  addBtn: {
    marginTop: theme.spacing.xs,
    border: `1px dashed ${theme.colors.input}`,
    borderRadius: theme.borderRadius.md,
    backgroundColor: "transparent",
    color: theme.colors.mutedForeground,
    cursor: "pointer",
    padding: `${theme.spacing.xs}px`,
    width: "100%",
    fontSize: theme.fontSize.md,
  },
  errorSlot: {
    minHeight: 20,
    marginTop: 2,
  },
  error: {
    fontSize: theme.fontSize.xs,
    color: theme.colors.destructive,
    margin: 0,
  },
});

const createModalStyles = (theme: Theme) => ({
  overlay: {
    position: "fixed" as const,
    inset: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 9999,
  },
  card: {
    backgroundColor: theme.colors.card,
    borderRadius: theme.borderRadius.xl,
    padding: theme.spacing.xxl,
    minWidth: 400,
    maxWidth: 640,
    maxHeight: "80vh",
    overflow: "auto",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.15)",
  },
  title: {
    fontSize: theme.fontSize.lg,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.foreground,
    marginBottom: theme.spacing.md,
  },
  body: {
    marginBottom: theme.spacing.xl,
  },
  actions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: theme.spacing.sm,
  },
  cancelButton: {
    padding: `${theme.spacing.sm}px ${theme.spacing.lg}px`,
    borderRadius: theme.borderRadius.md,
    minWidth: 80,
    textAlign: "center" as const,
    backgroundColor: theme.colors.secondary,
    color: theme.colors.secondaryForeground,
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.medium,
    border: "none",
    cursor: "pointer",
  },
  okButton: {
    padding: `${theme.spacing.sm}px ${theme.spacing.lg}px`,
    borderRadius: theme.borderRadius.md,
    minWidth: 80,
    textAlign: "center" as const,
    backgroundColor: theme.colors.primary,
    color: theme.colors.primaryForeground,
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.medium,
    border: "none",
    cursor: "pointer",
  },
});
