// playground/vue-quasar/src/presentation/components/SchemaTable.vue
<template>
  <div>
    <ActionBar
        :actions="table.actions"
        position="top"
        :domain="props.schema.domain"
    />

    <q-table
        :rows="table.rows"
        :columns="qColumns"
        :loading="table.loading"
        row-key="__identity"
        flat
        bordered
        :rows-per-page-options="[10, 25, 50]"
        :pagination="pagination"
        @update:pagination="onPagination"
    >
      <template #body-cell-__actions="cellProps">
        <q-td :props="cellProps" class="text-right">
          <SchemaButton
              v-for="action in table.getRowActions(cellProps.row)"
              :key="action.name"
              :action="action"
              :domain="props.schema.domain"
              flat
              dense
              size="sm"
              class="q-ml-xs"
          />
        </q-td>
      </template>

      <template #no-data>
        <div class="full-width text-center q-pa-lg text-grey">
          {{ t('common.table.empty') }}
        </div>
      </template>
    </q-table>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { useDataTable } from '@anhanga/vue'
import type { UseDataTableOptions } from '@anhanga/vue'
import ActionBar from './ActionBar.vue'
import SchemaButton from './SchemaButton.vue'

const props = defineProps<UseDataTableOptions>()

const { t, te } = useI18n()
const translateFn = (key: string, params?: Record<string, unknown>) => {
  if (!te(key)) return key
  return t(key, params ?? {})
}

const table = useDataTable({ ...props, translate: props.translate ?? translateFn })

const qColumns = computed(() => {
  const cols = table.columns.map((col) => {
    const fieldKey = `${props.schema.domain}.fields.${col.name}`
    return {
      name: col.name,
      label: te(fieldKey) ? t(fieldKey) : col.name,
      field: col.name,
      align: 'left' as const,
      sortable: true,
    }
  })
  cols.push({
    name: '__actions',
    label: te('common.table.actions') ? t('common.table.actions') : 'Actions',
    field: '__actions',
    align: 'right' as const,
    sortable: false,
  })
  return cols
})

const pagination = computed(() => ({
  page: table.page,
  rowsPerPage: table.limit,
  rowsNumber: table.total,
}))

function onPagination (p: { page: number; rowsPerPage: number }) {
  if (p.page !== table.page) table.setPage(p.page)
  if (p.rowsPerPage !== table.limit) table.setLimit(p.rowsPerPage)
}
</script>

// playground/sveltekit/src/lib/presentation/components/SchemaTable.svelte
<script lang="ts">
  import { useDataTable } from '@anhanga/svelte'
  import type { UseDataTableOptions } from '@anhanga/svelte'
  import { translate, hasTranslation } from '$lib/i18n'
  import ActionBar from './ActionBar.svelte'
  import SchemaButton from './SchemaButton.svelte'

  let props: UseDataTableOptions = $props()

  const defaultTranslate = (key: string, params?: Record<string, unknown>) => {
    if (!hasTranslation(key)) return key
    return translate(key, params)
  }

  const tableStore = useDataTable({
    schema: props.schema,
    scope: props.scope,
    handlers: props.handlers,
    hooks: props.hooks,
    context: props.context,
    component: props.component,
    pageSize: props.pageSize,
    translate: props.translate ?? defaultTranslate,
  })

  let table = $derived($tableStore)

  function columnLabel (name: string) {
    const key = `${props.schema.domain}.fields.${name}`
    return hasTranslation(key) ? translate(key) : name
  }
</script>

<div>
  <ActionBar actions={table.actions} position="top" domain={props.schema.domain} />

  {#if table.loading}
    <div class="loading-overlay">Loading...</div>
  {:else if table.empty}
    <div class="table-empty">
      {hasTranslation('common.table.empty') ? translate('common.table.empty') : 'No records found'}
    </div>
  {:else}
    <table>
      <thead>
        <tr>
          {#each table.columns as col (col.name)}
            <th onclick={() => tableStore.setSort(col.name)}>
              {columnLabel(col.name)}
              {#if table.sortField === col.name}
                {table.sortOrder === 'asc' ? ' \u25B2' : ' \u25BC'}
              {/if}
            </th>
          {/each}
          <th style="text-align: right">
            {hasTranslation('common.table.actions') ? translate('common.table.actions') : 'Actions'}
          </th>
        </tr>
      </thead>
      <tbody>
        {#each table.rows as row (tableStore.getIdentity(row))}
          <tr>
            {#each table.columns as col (col.name)}
              <td>{tableStore.formatValue(col.name, row[col.name], row)}</td>
            {/each}
            <td class="actions-cell">
              {#each tableStore.getRowActions(row) as action (action.name)}
                <SchemaButton {action} domain={props.schema.domain} flat small />
              {/each}
            </td>
          </tr>
        {/each}
      </tbody>
    </table>

    <div class="table-footer">
      <span>
        {translate('common.table.page', { page: table.page, total: table.totalPages })}
      </span>
      <div class="pagination">
        <button
          class="btn btn-default btn-sm"
          disabled={table.page <= 1}
          onclick={() => tableStore.setPage(table.page - 1)}
        >
          {translate('common.table.previous')}
        </button>
        <button
          class="btn btn-default btn-sm"
          disabled={table.page >= table.totalPages}
          onclick={() => tableStore.setPage(table.page + 1)}
        >
          {translate('common.table.next')}
        </button>
      </div>
    </div>
  {/if}
</div>
