// packages/vue-quasar/src/renderers/SelectField.vue
<template>
  <q-select
    v-if="!props.proxy.hidden"
    :model-value="props.value"
    :label="label"
    :options="options"
    :disable="props.proxy.disabled"
    :error="props.errors.length > 0"
    :error-message="props.errors[0]"
    emit-value
    map-options
    outlined
    dense
    @update:model-value="props.onChange($event)"
    @blur="props.onBlur()"
    @focus="props.onFocus()"
  />
</template>

<script setup lang="ts">
import { QSelect } from 'quasar'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import type { FieldRendererProps } from '@ybyra/vue'

const props = defineProps<FieldRendererProps>()
const { t, te } = useI18n()

const label = computed(() => {
  const key = `${props.domain}.fields.${props.name}`
  return te(key) ? t(key) : props.name
})

const options = computed(() => {
  const raw = (props.config.attrs.options ?? []) as (string | number)[]
  return raw.map((opt) => {
    const key = `${props.domain}.fields.${props.name}.${opt}`
    return { label: te(key) ? t(key) : String(opt), value: opt }
  })
})
</script>

// packages/sveltekit/src/renderers/SelectField.svelte
<script lang="ts">
  import { translate, hasTranslation } from '../i18n'

  let { domain, name, value, config, proxy, errors, onChange, onBlur, onFocus }: {
    domain: string
    name: string
    value: unknown
    config: { attrs: Record<string, unknown> }
    proxy: { hidden: boolean; disabled: boolean }
    errors: string[]
    onChange: (v: unknown) => void
    onBlur: () => void
    onFocus: () => void
  } = $props()

  let label = $derived(() => {
    const key = `${domain}.fields.${name}`
    return hasTranslation(key) ? translate(key) : name
  })

  let options = $derived((config.attrs.options ?? []) as (string | number)[])

  function optionLabel(opt: string | number): string {
    const key = `${domain}.fields.${name}.${opt}`
    return hasTranslation(key) ? translate(key) : String(opt)
  }
</script>

{#if !proxy.hidden}
  <div class="form-field" class:has-error={errors.length > 0}>
    <label for={name}>{label()}</label>
    <select
      id={name}
      value={String(value ?? '')}
      disabled={proxy.disabled}
      onchange={(e) => onChange(e.currentTarget.value)}
      onblur={() => onBlur()}
      onfocus={() => onFocus()}
    >
      <option value=""></option>
      {#each options as opt}
        <option value={String(opt)}>{optionLabel(opt)}</option>
      {/each}
    </select>
    {#if errors.length > 0}
      <span class="field-error">{errors[0]}</span>
    {/if}
  </div>
{/if}
