// packages/vue-quasar/src/renderers/ToggleField.vue
<template>
  <q-toggle
    v-if="!props.proxy.hidden"
    :model-value="Boolean(props.value)"
    :label="label"
    :disable="props.proxy.disabled"
    @update:model-value="props.onChange($event)"
  />
</template>

<script setup lang="ts">
import { QToggle } from 'quasar'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import type { FieldRendererProps } from '@anhanga/vue'

const props = defineProps<FieldRendererProps>()
const { t, te } = useI18n()

const label = computed(() => {
  const key = `${props.domain}.fields.${props.name}`
  return te(key) ? t(key) : props.name
})
</script>

// packages/sveltekit/src/renderers/ToggleField.svelte
<script lang="ts">
  import { translate, hasTranslation } from '../i18n'

  let { domain, name, value, proxy, onChange }: {
    domain: string
    name: string
    value: unknown
    proxy: { hidden: boolean; disabled: boolean }
    onChange: (v: unknown) => void
  } = $props()

  let label = $derived(() => {
    const key = `${domain}.fields.${name}`
    return hasTranslation(key) ? translate(key) : name
  })
</script>

{#if !proxy.hidden}
  <div class="toggle-field">
    <input
      id={name}
      type="checkbox"
      checked={Boolean(value)}
      disabled={proxy.disabled}
      onchange={(e) => onChange(e.currentTarget.checked)}
    />
    <label for={name}>{label()}</label>
  </div>
{/if}
