// playground/app/person/add.tsx
import { useMemo } from "react";
import { useTranslation } from "react-i18next";
import { Scope } from "@anhanga/core";
import { PersonSchema } from "../../src/domain/person/schema";
import { personEvents } from "../../src/domain/person/events";
import { personHandlers } from "../../src/domain/person/handlers";
import { personHooks } from "../../src/domain/person/hooks";
import { createComponent } from "../../src/presentation/contracts/component";
import { useDialog } from "../../src/presentation/components/Dialog";
import { SchemaForm } from "../../src/presentation/components/SchemaForm";
import { Page } from "../../src/presentation/components/Page";
import { scopes } from "./@routes";

export default function PersonAddPage () {
  const { t } = useTranslation();
  const dialog = useDialog();
  const component = useMemo(
    () => createComponent(Scope.add, scopes, dialog),
    [dialog],
  );

  return (
    <Page
      domain={PersonSchema.domain}
      scope={Scope.add}
    >
      <SchemaForm
        schema={PersonSchema.provide()}
        scope={Scope.add}
        events={personEvents}
        handlers={personHandlers}
        hooks={personHooks}
        component={component}
        translate={t}
      />
    </Page>
  );
}

// playground/sveltekit/src/routes/person/add/+page.svelte
<script lang="ts">
import { goto } from "$app/navigation";
import { scopes } from "$lib/routes/person";
import { personHandlers, personHooks } from "$lib/setup";
import { Scope } from "@anhanga/core";
import { allPermissions, personEvents, PersonSchema } from "@anhanga/demo";
import { createComponent, DataForm, DataPage } from "@anhanga/sveltekit";

const person = PersonSchema.provide();
const component = createComponent(Scope.add, scopes, goto);
</script>

<DataPage
  domain={person.domain}
  scope={Scope.add}
>
  <DataForm
    schema={person}
    scope={Scope.add}
    events={personEvents}
    handlers={personHandlers}
    hooks={personHooks}
    {component}
    permissions={allPermissions(person)}
  />
</DataPage>
