// playground/app/person/view/[id].tsx
import { useMemo } from "react";
import { useLocalSearchParams } from "expo-router";
import { useTranslation } from "react-i18next";
import { Scope } from "@anhanga/core";
import { PersonSchema, personEvents, personHandlers, personHooks } from "../../../src/domain/person";
import { createComponent } from "../../../src/presentation/contracts/component";
import { useDialog, SchemaForm, Page } from "../../../src/presentation/components";
import { scopes } from "../@routes";

export default function PersonViewPage () {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { t } = useTranslation();
  const dialog = useDialog();
  const component = useMemo(
    () => createComponent(Scope.view, scopes, dialog),
    [dialog],
  );

  return (
    <Page
      domain={PersonSchema.domain}
      scope={Scope.view}
    >
      <SchemaForm
        schema={PersonSchema.provide()}
        scope={Scope.view}
        events={personEvents}
        handlers={personHandlers}
        hooks={personHooks}
        context={{ id }}
        component={component}
        translate={t}
      />
    </Page>
  );
}

// playground/sveltekit/src/routes/person/[id]/+page.svelte
<script lang="ts">
import { goto } from "$app/navigation";
import { page } from "$app/state";
import { scopes } from "$lib/routes/person";
import { personHandlers, personHooks } from "$lib/setup";
import { Scope } from "@anhanga/core";
import { allPermissions, personEvents, PersonSchema } from "@anhanga/demo";
import { createComponent, DataForm, DataPage } from "@anhanga/sveltekit";

const id = page.params.id;
const person = PersonSchema.provide();
const component = createComponent(Scope.view, scopes, goto);
</script>

<DataPage
  domain={person.domain}
  scope={Scope.view}
>
  <DataForm
    schema={person}
    scope={Scope.view}
    events={personEvents}
    handlers={personHandlers}
    hooks={personHooks}
    context={{ id }}
    {component}
    permissions={allPermissions(person)}
  />
</DataPage>
