// packages/vue-quasar/src/renderers/TextareaField.vue
<template>
  <q-input
    v-if="!props.proxy.hidden"
    :model-value="String(props.value ?? '')"
    :label="label"
    :disable="props.proxy.disabled"
    :error="props.errors.length > 0"
    :error-message="props.errors[0]"
    :rows="rows"
    type="textarea"
    outlined
    dense
    @update:model-value="props.onChange($event)"
    @blur="props.onBlur()"
    @focus="props.onFocus()"
  />
</template>

<script setup lang="ts">
import { QInput } from 'quasar'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import type { FieldRendererProps } from '@ybyra/vue'

const props = defineProps<FieldRendererProps>()
const { t, te } = useI18n()

const label = computed(() => {
  const key = `${props.domain}.fields.${props.name}`
  return te(key) ? t(key) : props.name
})

const rows = computed(() => props.proxy.height || props.config.form.height || 3)
</script>

// packages/react-native/src/renderers/TextareaField.tsx
import { View, Text, TextInput, StyleSheet } from "react-native";
import { useTranslation } from "react-i18next";
import type { FieldRendererProps } from "@ybyra/react";
import { useTheme } from "../theme/context";
import type { Theme } from "../theme/default";
import { ds } from "../support/ds";

export function TextareaField({ domain, name, value, config, proxy, errors, onChange, onBlur, onFocus }: FieldRendererProps) {
  const { t, i18n } = useTranslation();
  const theme = useTheme();
  const styles = createStyles(theme);
  if (proxy.hidden) return null;

  const fieldLabel = t(`${domain}.fields.${name}`, { defaultValue: name });
  const placeholderKey = `${domain}.fields.${name}.placeholder`;
  const placeholder = i18n.exists(placeholderKey) ? t(placeholderKey) : undefined;
  const numberOfLines = proxy.height || config.form.height || 3;

  return (
    <View style={styles.container} {...ds(`TextareaField:${name}`)}>
      <Text style={styles.label}>{fieldLabel}</Text>
      <TextInput
        style={[styles.input, proxy.disabled && styles.inputDisabled, errors.length > 0 && styles.inputError]}
        value={String(value ?? "")}
        onChangeText={onChange}
        onBlur={onBlur}
        onFocus={onFocus}
        editable={!proxy.disabled}
        placeholder={placeholder}
        placeholderTextColor={theme.colors.mutedForeground}
        multiline
        numberOfLines={numberOfLines}
        textAlignVertical="top"
      />
      <View style={styles.errorSlot}>
        {errors.map((error, i) => (
          <Text key={i} style={styles.error}>{error}</Text>
        ))}
      </View>
    </View>
  );
}

const createStyles = (theme: Theme) => StyleSheet.create({
  container: {
    paddingHorizontal: theme.spacing.xs,
  },
  label: {
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.semibold,
    marginBottom: theme.spacing.xs,
    color: theme.colors.foreground,
  },
  input: {
    borderWidth: 1,
    borderColor: theme.colors.input,
    borderRadius: theme.borderRadius.md,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 10,
    fontSize: theme.fontSize.md,
    backgroundColor: theme.colors.card,
    color: theme.colors.cardForeground,
  },
  inputDisabled: {
    backgroundColor: theme.colors.muted,
    color: theme.colors.mutedForeground,
  },
  inputError: {
    borderColor: theme.colors.destructive,
  },
  errorSlot: {
    minHeight: 20,
    marginTop: 2,
  },
  error: {
    fontSize: theme.fontSize.xs,
    color: theme.colors.destructive,
  },
});
