// playground/react-native/src/presentation/components/SchemaForm.tsx
import { useCallback, useState } from "react";
import { View, Text, Pressable, StyleSheet, Platform, ActivityIndicator } from "react-native";
import { useTranslation } from "react-i18next";
import { Feather } from "@expo/vector-icons";
import { useSchemaForm, getRenderer } from "@anhanga/react";
import type { UseSchemaFormOptions, ResolvedField, UseSchemaFormReturn } from "@anhanga/react";
import { fakeAll } from "@anhanga/demo";
import { theme } from "../theme";
import { ActionBar } from "./ActionBar";
import "./renderers";

const ds = (id: string) => ({ dataSet: { id } }) as any;

interface SchemaFormProps extends UseSchemaFormOptions {
  debug?: boolean;
}

function reload () {
  if (Platform.OS === "web" && typeof window !== "undefined") {
    window.location.reload();
  }
}

function FieldsGrid ({ fields, getFieldProps }: {
  fields: ResolvedField[];
  getFieldProps: UseSchemaFormReturn["getFieldProps"]
}) {
  return (
    <View style={styles.fieldsGrid}>
      {fields.map((field) => {
        if (field.proxy.hidden) return null;
        const Renderer = getRenderer(field.config.component);
        if (!Renderer) return null;
        return (
          <View
            key={field.name}
            style={{ gridColumn: `span ${field.proxy.width}` } as any}
            {...ds(`field:${field.name}`)}
          >
            <Renderer {...getFieldProps(field.name)} />
          </View>
        );
      })}
    </View>
  );
}

export function SchemaForm ({ debug = __DEV__, ...props }: SchemaFormProps) {
  const { t } = useTranslation();
  const form = useSchemaForm({ ...props, translate: props.translate ?? t });
  const [debugExpanded, setDebugExpanded] = useState(false);

  const handleFill = useCallback(() => {
    const fakeData = fakeAll(props.schema.fields, props.schema.identity);
    form.setValues(fakeData);
  }, [props.schema.fields, props.schema.identity, form]);

  if (form.loading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" />
      </View>
    );
  }

  return (
    <View {...ds("SchemaForm")}>
      <ActionBar
        actions={form.actions}
        position="top"
        domain={props.schema.domain}
      />

      {form.sections.map((section, index) => {
        if (section.kind === "group") {
          return (
            <View
              key={section.name}
              style={styles.group} {...ds(`group:${section.name}`)}>
              <Text style={styles.groupTitle}>{t(`${props.schema.domain}.groups.${section.name}`, { defaultValue: section.name })}</Text>
              <FieldsGrid
                fields={section.fields}
                getFieldProps={form.getFieldProps}
              />
            </View>
          );
        }
        return (
          <View
            key={`ungrouped-${index}`}
            style={styles.group} {...ds("ungrouped")}>
            <FieldsGrid
              fields={section.fields}
              getFieldProps={form.getFieldProps}
            />
          </View>
        );
      })}

      <View style={styles.divider} />

      <ActionBar
        actions={form.actions}
        position="footer"
        domain={props.schema.domain}
      />

      <ActionBar
        actions={form.actions}
        position="floating"
        domain={props.schema.domain}
      />

      {debug && (
        <View style={styles.debugSection} {...ds("debug")}>
          <View style={styles.debugToolbar}>
            <View style={styles.debugActions}>
              <Pressable
                style={styles.debugButton}
                onPress={handleFill}
              >
                <Feather
                  name="zap"
                  size={12}
                  color={theme.colors.warning}
                />
              </Pressable>
              <Pressable
                style={styles.debugButton}
                onPress={() => form.reset()}
              >
                <Feather
                  name="rotate-ccw"
                  size={12}
                  color={theme.colors.mutedForeground}
                />
              </Pressable>
              <Pressable
                style={styles.debugButton}
                onPress={() => form.validate()}
              >
                <Feather
                  name="check"
                  size={12}
                  color={theme.colors.success}
                />
              </Pressable>
              <Pressable
                style={styles.debugButton}
                onPress={reload}
              >
                <Feather
                  name="refresh-cw"
                  size={12}
                  color={theme.colors.info}
                />
              </Pressable>
              <Pressable
                style={styles.debugButton}
                onPress={() => setDebugExpanded((v) => !v)}
              >
                <Feather
                  name={debugExpanded ? "minus" : "plus"}
                  size={12}
                  color={theme.colors.warning}
                />
              </Pressable>
            </View>
          </View>

          {debugExpanded && (
            <>
              <Text style={styles.debugTitle}>State</Text>
              <Text style={styles.debugText}>
                {JSON.stringify(form.state, null, 2)}
              </Text>
              <Text style={styles.debugTitle}>Errors</Text>
              <Text style={styles.debugText}>
                {JSON.stringify(form.errors, null, 2)}
              </Text>
              <Text style={styles.debugMeta}>
                dirty: {String(form.dirty)} | valid: {String(form.valid)}
              </Text>
            </>
          )}
        </View>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  loadingContainer: {
    paddingVertical: theme.spacing.xxl,
    alignItems: "center",
    justifyContent: "center",
  },
  group: {
    marginBottom: theme.spacing.lg,
  },
  groupTitle: {
    fontSize: theme.fontSize.md,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.mutedForeground,
    marginBottom: theme.spacing.md,
  },
  fieldsGrid: {
    display: "grid" as any,
    gridTemplateColumns: "repeat(100, 1fr)",
  } as any,
  divider: {
    height: 1,
    backgroundColor: theme.colors.border,
    marginVertical: theme.spacing.xl,
  },
  debugSection: {
    marginTop: theme.spacing.xxl,
    padding: theme.spacing.lg,
    backgroundColor: theme.colors.foreground,
    borderRadius: theme.borderRadius.md,
  },
  debugToolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: theme.spacing.sm,
    marginBottom: theme.spacing.md,
  },
  debugActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  debugButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: theme.borderRadius.sm,
    backgroundColor: "#374151",
  },
  debugTitle: {
    fontSize: theme.fontSize.xs,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.mutedForeground,
    marginBottom: 2,
    marginTop: 10,
  },
  debugText: {
    fontSize: theme.fontSize.xs,
    fontFamily: "monospace",
    color: theme.colors.border,
  },
  debugMeta: {
    fontSize: theme.fontSize.xs,
    color: theme.colors.mutedForeground,
    marginTop: 10,
  },
});

// playground/vue-quasar/src/presentation/components/SchemaForm.vue
<template>
  <div
      v-if="form.loading"
      class="text-center q-pa-lg text-grey"
  >
    <q-spinner
        size="2em"
        class="q-mr-sm"
    />
    Loading...
  </div>

  <div v-else>
    <ActionBar
        :actions="form.actions"
        position="top"
        :domain="props.schema.domain"
    />

    <div
        v-for="(section, index) in form.sections"
        :key="section.kind === 'group' ? section.name : `ungrouped-${index}`"
        class="q-mb-lg"
    >
      <div
          v-if="section.kind === 'group'"
          class="q-mb-sm text-subtitle2 text-grey-7"
      >
        {{ resolveGroup(section.name) }}
      </div>
      <div class="row q-col-gutter-md">
        <template
            v-for="field in section.fields"
            :key="field.name"
        >
          <div
              v-if="!field.proxy.hidden"
              :class="`col-${Math.round(field.proxy.width * 12 / 100)}`"
          >
            <component
                :is="getRenderer(field.config.component)"
                v-if="getRenderer(field.config.component)"
                v-bind="form.getFieldProps(field.name)"
            />
          </div>
        </template>
      </div>
    </div>

    <q-separator class="q-my-lg" />

    <ActionBar
        :actions="form.actions"
        position="footer"
        :domain="props.schema.domain"
    />

    <div
        v-if="debug"
        class="q-mt-lg q-pa-md bg-dark rounded-borders"
    >
      <div class="row q-gutter-xs q-mb-sm">
        <q-btn
            dense
            flat
            icon="flash_on"
            size="sm"
            color="amber"
            @click="handleFill"
        />
        <q-btn
            dense
            flat
            icon="restart_alt"
            size="sm"
            color="grey"
            @click="form.reset()"
        />
        <q-btn
            dense
            flat
            icon="check"
            size="sm"
            color="green"
            @click="form.validate()"
        />
        <q-btn
            dense
            flat
            icon="refresh"
            size="sm"
            color="blue"
            @click="() => globalThis.location.reload()"
        />
        <q-btn
            dense
            flat
            :icon="debugExpanded ? 'remove' : 'add'"
            size="sm"
            color="amber"
            @click="debugExpanded = !debugExpanded"
        />
      </div>

      <template v-if="debugExpanded">
        <div class="text-caption text-grey-5 q-mt-sm">State</div>
        <pre
            class="text-caption text-grey-3"
            style="white-space: pre-wrap"
        >{{ JSON.stringify(form.state, null, 2) }}</pre>
        <div class="text-caption text-grey-5 q-mt-sm">Errors</div>
        <pre
            class="text-caption text-grey-3"
            style="white-space: pre-wrap"
        >{{ JSON.stringify(form.errors, null, 2) }}</pre>
        <div class="text-caption text-grey-5 q-mt-sm">
          dirty: {{ form.dirty }} | valid: {{ form.valid }}
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useSchemaForm, getRenderer } from '@anhanga/vue'
import type { UseSchemaFormOptions } from '@anhanga/vue'
import { fakeAll } from '@anhanga/demo'
import ActionBar from './ActionBar.vue'

interface SchemaFormProps extends UseSchemaFormOptions {
  debug?: boolean
}

const props = withDefaults(defineProps<SchemaFormProps>(), {
  debug: true,
})

const { t, te } = useI18n()
const translateFn = (key: string, params?: Record<string, unknown>) => {
  if (!te(key)) return key
  return t(key, params ?? {})
}

const form = useSchemaForm({ ...props, translate: props.translate ?? translateFn })
const debugExpanded = ref(false)

function resolveGroup (name: string) {
  const key = `${props.schema.domain}.groups.${name}`
  return te(key) ? t(key) : name
}

function handleFill () {
  const fakeData = fakeAll(props.schema.fields, props.schema.identity)
  form.setValues(fakeData)
}
</script>
