// playground/react-web/src/pages/PersonList.tsx
import { scopes } from "@/pages/@routes";
import { personHandlers, personHooks } from "@/setup";
import { Scope } from "@anhanga/core";
import { PersonSchema } from "@anhanga/demo";
import { DataTable, Page, useComponent } from "@anhanga/react-web";
import { useNavigate } from "react-router-dom";

export function PersonList () {
  const navigate = useNavigate();
  const component = useComponent(Scope.index, scopes, navigate);

  return (
    <Page
      domain={PersonSchema.domain}
      scope={Scope.index}
    >
      <DataTable
        schema={PersonSchema.provide()}
        scope={Scope.index}
        handlers={personHandlers}
        hooks={personHooks}
        component={component}
        pageSize={3}
        debug={true}
      />
    </Page>
  );
}

// playground/vue-quasar/src/pages/PersonList.vue
<template>
  <DataPage
    :domain="'person'"
    :scope="Scope.index"
  >
    <DataTable
      :schema="person"
      :scope="Scope.index"
      :handlers="personHandlers"
      :hooks="personHooks"
      :component="component"
      :permissions="allPermissions(person)"
      :page-size="10"
    />
  </DataPage>
</template>

<script
  setup
  lang="ts"
>
import { personHandlers, personHooks } from "@/setup";
import { Scope } from "@anhanga/core";
import { allPermissions, PersonSchema } from "@anhanga/demo";
import { DataPage, DataTable, useComponent } from "@anhanga/vue-quasar";
import { scopes } from "./person/@routes";

const person = PersonSchema.provide();
const component = useComponent(Scope.index, scopes);
</script>
